### ISSUE TITLE
Isssue regarding setting up the etherium testnet.

### ISSUE THREAD

**Issue by kushagra9999** [yenxuan1381/anti-counterfeit-product-identification-system-using-blockchain#2]
I have connected the database on my side and also the project is working but it is not working in full functionality since maybe I am don't know if I am connecting my wallet in right way . I don't know what to include in .env file and this is my first project working with smart contracts so I am having some issue with it .  Also my laptop camera is not good and it takes lot of time scanning the qr is it it possible to add upload qr functionality along with scanning qr code for easier experience. Any help would be much appreciated . Thank you.

**Comment by yenxuan1381** [comment]
Hi, Kushagra. I'm glad you have interest in this project. However, this is just a showcase of the full functionality of the product and is not actively maintained. It would be great if you could contribute to this project with the upload qr code functionality.

Regarding the .env file, it is on the smart contract and it has already been deployed to the Sepolia testnet. Hence, there is nothing to worry about. No changes need to be made to this file.

As for setting up the ethereum testnet, pls refer to: https://moralis.io/how-to-add-the-sepolia-network-to-metamask-full-guide/

**Comment by kushagra9999** [comment]
Thanks I'll try to work on it.
